### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'C:\C:\Users\s\Downloads\valro-lfg-master\valro-lfg-master\dist\commands'

### ISSUE THREAD

**Issue by xpboosting** [Sans3108/valro-lfg#1]
[https://imgur.com/a/cXH8NMb](url)

**Comment by Sans3108** [comment]
Note: OS: Windows 11
Node: Latest

**Comment by Sans3108** [comment]
Seems to only be an issue on Windows/Windows based systems

I was able to replicate it on Windows but on WSL and my Ubuntu Server it works just fine

![](https://media.discordapp.net/attachments/649325430326689823/1065077340209688697/image.png)

**Comment by Sans3108** [comment]
Fixed
